# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 1200s
options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: 'gcr.io/k8s-testimages/gcb-docker-gcloud:v20210722-085d930'
    entrypoint: make
    env:
    - TAG=$PULL_BASE_REF
    - GIT_COMMIT=$PULL_BASE_SHA
    args:
    - push
